### ISSUE TITLE
Setup comments

### ISSUE THREAD

**Issue by ytakemon** [smcclatchy/mapping#1]
1. Currently creating an Rproject is an option. In that case, it would be good to start everyone in the same directory to prevent future directory confusions. For example, it might be easy to have everyone make a directory called "mapping" on their desktop and run the following before creating new directories:

``` setting up directories:
setwd("~/Desktop")
dir.create("./mapping")
setwd("~/Desktop/mapping")
dir.create("./data")
dir.create("./scripts")
dir.create("./results")
```
2. Downloading DOQTL data:
It should be said that once the data have been downloaded, it should be put into the ~/Desktop/mapping/data directory. 

3. Initial steps that demonstrate reading data is a bit confusing because grav2.yaml wasn't downloaded yet. Where do you get it? There is no link. Also It might be better to either have participants go download the grav2.yaml first and put it into their data directory then the demo, or just read from Karl's website directly but showing all the different ways might be a bit confusing:
```
library(qtl2geno)
grav2 <- read_cross2("http://kbroman.org/qtl2/assets/sampledata/grav2/grav2.zip")
#or download into directory first then:
grav2 <- read_cross2("~/my_data/grav2.yaml")
```

4. write_control_file() was mentioned at the very end lacks explanation. It looks like a pretty useful function so if it's is going to be mentioned might as well provide some examples for its use? This example was taken from the documentation:
```
?write_control_file()

write_control_file("~/my_data/grav2.yaml",
                        crosstype="riself",
                        geno_file="grav2_geno.csv",
                        gmap_file="grav2_gmap.csv",
                        pheno_file="grav2_pheno.csv",
                        phenocovar_file="grav2_phenocovar.csv",
                        geno_codes=c(L=1L, C=2L),
                        alleles=c("L", "C"),
                        na.strings=c("-", "NA"))
```

**Comment by smcclatchy** [comment]
Thanks for these suggestions, Yuka. I simplified the setup instructions considerably and added the code block that you wrote.

Sue
