### ISSUE TITLE
Introduction comments:

### ISSUE THREAD

**Issue by ytakemon** [smcclatchy/mapping#2]
1. Sample datasets: read_cross step is redundant from previous set up page. I think the two steps should be collapsed so you don't end up doing the same thing in 5 different steps, which seems to be the easiest way to confuse people (ie me :) ).
```
# Redudant:
grav2 <- read_cross2( system.file("extdata", "grav2.zip", package="qtl2geno") )
grav2 <- read_cross2("http://kbroman.org/qtl2/assets/sampledata/grav2/grav2.zip")
grav2 <- read_cross2("~/my_data/grav2.zip")
zip_datafiles("~/my_data/grav2.yaml")
grav2 <- read_cross2("~/my_data/grav2.yaml")

# From all these I think the easiest method is:
grav2 <- read_cross2( system.file("extdata", "grav2.zip", package="qtl2geno") )
# but it would be good for everyone to download the sample data into their own directory 
# and learn to load data from their own machines:
grav2 <- read_cross2("~/my_data/grav2.yaml")
```

**Comment by smcclatchy** [comment]
Thanks for this, too, Yuka. I got rid of this entirely because it doesn't really meet learning goals - rather, it gets in the way.

Sue

**Comment by ytakemon** [comment]
I just took another look, and it looks great! I've never seen a visual workflow for qtl anlalysis, and I think it'll help with the mental conceptualization of the workshop. Where was this when I was learning this?!
