### ISSUE TITLE
Calculating Genotype Probabilities commets

### ISSUE THREAD

**Issue by ytakemon** [smcclatchy/mapping#4]
I think this page is very well constructed! It flows very nicely and the explanations a very clear. 

1. One part I noticed that wasn't explained was how to know what the error_probability. How do you determine the error_prob? A short explanation would be nice here: 
```
# How did you get 0.002?
pr <- calc_genoprob(cross=iron, map=map, error_prob=0.002)
```

**Comment by smcclatchy** [comment]
Thanks for this @ytakemon - I included an explanation of assumed genotyping error rate. It's more of an assumption based on what you know about how genotyping was conducted.
